version: '3.8'
services:
  app:
    container_name: main_app
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: database
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    container_name: test_cont
    build: .
    depends_on:
      - db
    env_file:
      - tests/.env
    command: go test ./...
    volumes:
      - .:/app


volumes:
  postgres_data: